version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ride_hailing_db
    environment:
      POSTGRES_DB: ride_hailing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ride_hailing_network

  redis:
    image: redis:7-alpine
    container_name: ride_hailing_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ride_hailing_network
    command: redis-server --appendonly yes

  backend:
    build: .
    container_name: ride_hailing_backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ride_hailing?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - ride_hailing_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  ride_hailing_network:
    driver: bridge